version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  app:
    depends_on:
      - db
    container_name: app
    build: .
    command: bash -c "rails db:setup && rails server"
    ports:
      - "3000:8080"