version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  app:
    depends_on:
      - db
    container_name: app
    build: .
    command: bash -c "rails db:setup && rails server -b 0.0.0.0"
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    depends_on:
      - app